// @ts-nocheck
import Layout from "../components/Layout";

export default function Profile() {
  const user = JSON.parse(localStorage.getItem("user")) || {};
  const allBookings =
    JSON.parse(localStorage.getItem("bookings")) || [];

  // ✅ only this user's bookings
  const userBookings = allBookings.filter(
    (b) => b.email === user.email
  );

  const total = userBookings.length;

  // last booking → upcoming
  const upcoming =
    total > 0 ? userBookings[total - 1] : null;

  // before last → previous therapists
  const previousTherapists =
    total > 1 ? userBookings.slice(0, total - 1) : [];

  /* ---------- PDF DOWNLOAD (SAMPLE REPORT) ---------- */
  const downloadPDF = (booking, index) => {
    const content = `
CALMPATH – THERAPIST REPORT

Client Name: ${user.name}
Client Email: ${user.email}

Therapist: ${booking.doctorName}
Specialty: ${booking.specialty}
Session Date: ${booking.date}
Session Time: ${booking.time}

----------------------------------------

Clinical Summary:
The client demonstrated steady emotional progress
and engaged positively during the session.

Key Observations:
• Improved emotional awareness
• Better stress handling
• Active participation

Recommendations:
• Continue weekly therapy
• Practice mindfulness
• Maintain journaling

----------------------------------------
Generated by CalmPath
    `;

    const blob = new Blob([content], {
      type: "application/pdf",
    });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `Therapist_Report_${index + 1}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Layout>
      <div style={page}>
        <h2 style={title}>👤 My Profile</h2>

        {/* USER INFO */}
        <section style={card}>
          <p><b>Name:</b> {user.name}</p>
          <p><b>Email:</b> {user.email}</p>
          <p><b>Total Sessions:</b> {total}</p>
        </section>

        {/* UPCOMING SESSION */}
        <section style={card}>
          <h3 style={sectionTitle}>⏳ Upcoming Session</h3>

          {upcoming ? (
            <>
              <p><b>Therapist:</b> {upcoming.doctorName}</p>
              <p><b>Specialty:</b> {upcoming.specialty}</p>
              <p><b>Date:</b> {upcoming.date}</p>
              <p><b>Time:</b> {upcoming.time}</p>

              {/* Meet link if you want it here */}
              <a
                href={upcoming.meetLink}
                target="_blank"
                rel="noreferrer"
                style={meetLink}
              >
                Join Google Meet
              </a>
            </>
          ) : (
            <p>No upcoming sessions</p>
          )}
        </section>

        {/* PREVIOUS THERAPIST REPORTS */}
        {previousTherapists.length > 0 && (
          <section style={card}>
            <h3 style={sectionTitle}>
              📄 Previous Therapist Reports
            </h3>

            {previousTherapists.map((b, i) => (
              <div key={i} style={pdfCard}>
                <p><b>Therapist:</b> {b.doctorName}</p>
                <p><b>Specialty:</b> {b.specialty}</p>
                <p><b>Date:</b> {b.date}</p>
                <p><b>Time:</b> {b.time}</p>

                <button
                  style={downloadBtn}
                  onClick={() => downloadPDF(b, i)}
                >
                  ⬇ Download PDF Report
                </button>
              </div>
            ))}
          </section>
        )}

        {/* GOOD FEEL LINE */}
        <div style={quote}>
          🌿 <i>
            Healing is progress, not perfection.
            You’re moving forward — and that matters.
          </i>
        </div>
      </div>
    </Layout>
  );
}

/* ---------- STYLES ---------- */

const page = {
  minHeight: "100vh",
  padding: "30px",
  backgroundColor: "#f4f9f6",
};

const title = {
  color: "#2d6a4f",
  marginBottom: "20px",
};

const sectionTitle = {
  color: "#2d6a4f",
  marginBottom: "12px",
};

const card = {
  backgroundColor: "white",
  padding: "20px",
  borderRadius: "12px",
  marginBottom: "20px",
  boxShadow: "0 4px 14px rgba(0,0,0,0.08)",
};

const pdfCard = {
  backgroundColor: "#fafafa",
  border: "1px solid #ddd",
  padding: "16px",
  borderRadius: "10px",
  marginBottom: "14px",
};

const downloadBtn = {
  marginTop: "8px",
  padding: "10px",
  width: "100%",
  backgroundColor: "#2d6a4f",
  color: "white",
  border: "none",
  borderRadius: "8px",
  cursor: "pointer",
};

const meetLink = {
  display: "inline-block",
  marginTop: "8px",
  color: "#2d6a4f",
  fontWeight: "600",
};

const quote = {
  backgroundColor: "#e9f5ec",
  padding: "18px",
  borderRadius: "12px",
  textAlign: "center",
};
